### ISSUE TITLE
Handle conection return code

### ISSUE THREAD

**Issue by ridnarong** [netpieio/microgear-python#10]
4: Invalid token -- Reset stored access token 
5: Unauthorized or disabled key -- Try to reconnect with existing access token

**Comment by chaiwith** [comment]
Handle connection return 4,5 and improve unsubscripted method.

**Comment by ridnarong** [comment]
พี่ยังไม่แน่ใจนะเรื่อง return 4,5 ลองใส่ key แล้วไป disable กับ delete token แล้วใช่ไหม ดูว่ามันมีอาการอะไร แล้ว return อะไร ถามดูให้แน่ใจ
