### ISSUE TITLE
Cache structure

### ISSUE THREAD

**Issue by ridnarong** [netpieio/microgear-python#12]
add `key` to object and maintain compatability.
Handle invalid cache. 
When current `key` is not match with `key` in cache send revoke token then clear credential in cache.

**Comment by chaiwith** [comment]
add key to cache and set requesttoken is null when generated accesstoken https://github.com/chaiwith/microgear-python/commit/81a1b8eff87803370ddd79c4ed3eadedf15b2b16

**Comment by ridnarong** [comment]
ตรงบรรทัดที่ 231
```python
    if cached and cached.get("accesstoken"):
        microgear.accesstoken = cached.get("accesstoken")
        for name,value in microgear.accesstoken.items():
            microgear.accesstoken[name] = str(value)
    else:
        cached = cache.set_item("microgear.cache", {})
        cached["key"] = microgear.gearkey
        cache.set_item("microgear.cache", cached) 
```
อยากให้ check ด้วยว่า ถ้ามี access token แล้ว มันเป็นเป็น key เดียวกันหรือเปล่าระหว่าง ใน cache กับ ใน code ถ้าคนละ key ก็ส่ง resettoken() ไปก่อนเพื่อลบ access token เก่าก่อน และลบใน cache ออก

**Comment by ridnarong** [comment]
Improve in https://github.com/netpieio/microgear-python/commit/2970da10ea0a398a3905c552832c70fcf8d90207
